[workspace]
members = [
    "balls_driver",
    "balls_span",
    "balls_bytecode",
    "balls_compiler",
    "balls_vm",
]
resolver = "2"

[workspace.dependencies]
camino = "1.1.7"
chumsky = "1.0.0-alpha.7"
clap = "4.5.4"
codespan-reporting = "0.11.1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
multiple_unsafe_ops_per_block = "warn"
alloc_instead_of_core = "warn"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
